# Things Numpy adds to the python ecosystem

* powerful and fast array creation and access functions optimized for vector functions
    * broadcasting (for arrays of different shapes) helps vectorize arrays so that loops occur in C instead of Python
* linear algebra
* fourier transforms
* random number generation



## Python indices are "zero-based"

* The center of the origin pixel is index 0
* e.g. for a 2D array the origin pixel (lower-left) is [0, 0]

### Comparisons to other languages/applications:

* 0-based indexing:  python, C, IDL
* 1-based indexing:  fortran, IRAF, FITS WCS, SExtractor, DS9

## Python arrays are stored in "row-major" order

* for a 2D array, if x is the column index and y is the row index, then
the array is indexed as **[y, x]**
  * e.g. **data[y, x]**
  * *x (column) is the fast array index and y (row) is the slow array index*, this has meaning when the data are stored in memory
* for a 3D array, index as e.g. **data[z, y, x]**

## A good way of looking at this visually is to check out the flatten() function, which will arrange the rows in the order they appear in memory. It's possible to choose the memory order of the flatten as well, specified by 'C' style or 'F'ortran style

In [ ]:
import numpy as np    # standard convention for importing numpy and using it in your code

In [ ]:
# define a 2D (2x3) array
b = np.array([[0, 1, 2], 
              [3, 4, 5]])
print(b)
b.shape

In [ ]:
b.flatten() # default

In [ ]:
b.flatten('C') # row major

In [ ]:
b.flatten('F') # column major

## Numpy multidimensional arrays are known as  ndarrays:
* an array of homogeneous elements, usually numbers, all of the same type
* a memory-efficient container that provides fast numerical operations
* designed for scientific computation (array-oriented computing)
* in numpy, the dimensions are called axes, and the number of axes is the rank

# Creating and examining arrays

In [ ]:
# define a 1D array of 4 elements as a list, this is a rank 1 array because there is only 1 dimension
a = np.array(1,2,3,4)  # This Doesn't work!
a

In [ ]:
# You need to call array with a defined list of numbers
a = np.array([0, 1, 2, 3]) # This works!
a

In [ ]:
# make an array with values ranging from 0 to 9
c = np.arange(10)
c

In [ ]:
d = np.arange(2, 5, 0.5)  # array start, stop (exclusive), step
d

In [ ]:
# 10 numbers between 2 and 4, inclusive
e = np.linspace(2, 4, 10)
e

In [ ]:
# make a 3x3 array of zeros
f = np.zeros((3, 3))
f

In [ ]:
# Create a 3x3 array of random floats
f = np.random.rand(3,3)
f

# Array attributes

In [ ]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) 
a

In [ ]:
# number of dimensions
a.ndim

In [ ]:
# the shape of the array
a.shape

In [ ]:
# the number of elements in the array
a.size

In [ ]:
# the data type of the array
a.dtype

# Basic mathematical operations

* arithmetic operators are applied *elementwise*

In [ ]:
a + 10

In [ ]:
a ** 3

In [ ]:
a + (2 * a)

In [ ]:
# elementwise multiplication, not matrix multiplication
a * a   

In [ ]:
# matrix multiplication
np.dot(a, a)
# a.dot(a)   # shorthand for above

In [ ]:
# in-place modification (memory efficient)
a *= 3
a

# Unary operations
* computations on arrays, or parts of arrays when the axis is specified

In [ ]:
# np.sum(a)
a.sum()   # shorthand for above

In [ ]:
a.mean(), a.std()

# Universal functions (also known as ufuncs)
* these are your standard mathematical functions, such as sin, cos ....

In [ ]:
x = np.arange(5)
np.exp(x)

In [ ]:
np.sqrt(x)

In [ ]:
np.sin(x)

# Indexing and slicing
* one dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences

In [ ]:
# an array with cubes all numbers from 0-9
x = np.arange(10)**3
x

In [ ]:
# the fourth element in x
x[3]

In [ ]:
x[-1]  # last index

In [ ]:
x[-2]  # second-to-last index

In [ ]:
# slicing, taking pieces of the array
x[3:6]  # does not include x[6], endpoint is exclusive!

In [ ]:
x[5:]  # shorthand for x[5:len(x)]

In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

**if fancy indexing seems time consuming for your application you can try using take() or compress() which are often faster**

In [ ]:
# fancy indexing:  specify the array locations of the values you want
idx = [5, 2, 1]
x[idx]

In [ ]:
# fancy indexing with mask arrays
idx = (x > 300)
idx

In [ ]:
x[idx]

In [ ]:
print(x)
x.take([5,2,1]) # notice the automatic flatten happen?

In [ ]:
print("a is: \n",a)
np.take(a,[0],axis=1)

# For further information:

Numpy

* http://www.numpy.org

* https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

SciPy is an open source package for science, math and engineering and contains additional useful routines including FFTs, integration, linear algebra, sparse matrices and statistics

* https://www.scipy.org/

* https://www.scipy.org/getting-started.html




## Exercises!  

<li>Create an array which has random numbers, and extract just the integer portion using several different methods:   

sample = np.random.uniform(0,10,10)


    [ 6.45190013  8.60697096  9.92051814  6.57861221  5.00177762  7.51331849
      7.48474007  8.73975799  3.53513788  9.5467646 ]


You should get answers similar to this:


    [ 6.  8.  9.  6.  5.  7.  7.  8.  3.  9.]
    [ 6.  8.  9.  6.  5.  7.  7.  8.  3.  9.]
    [ 6.  8.  9.  6.  5.  7.  7.  8.  3.  9.]
    [6 8 9 6 5 7 7 8 3 9]
    [ 6.  8.  9.  6.  5.  7.  7.  8.  3.  9.]

<b>Change this cell (this one, with the text you are reading) to a code cell to see the answers.....
<!--hide answer 
print (sample - sample%1)
print (np.floor(sample))
print (np.ceil(sample)-1)
print (sample.astype(int))
print (np.trunc(sample)) 
-->

<li> Take this array:

sample = np.array([1,2,3,4,5])

And place 2 zeros between every number

<b>Make this a code cell to see the answer....
<!--hide answer
sample = np.array([1,2,3,4,5])
zeros = 2
zero_array = np.zeros(len(sample) + (len(sample)-1)*(zeros))
print(zero_array[::])
zero_array[::zeros+1] = sample
print(zero_array)
-->